spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.101/sell?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql:true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.56.101
    port: 6379

server:
  context-path: /sell

wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: dc6085ac5a4f26c4e34835a53c87f2ae
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 7mdApPMfXddfWWbbP4DUaVYm2wjyh3v3
  keyPath: C:\Program Files\Java\h5.p12
  notifyUrl: http://dwight.natapp4.cc/sell/pay/notify


projectUrl:
  wechatMpAuthorize: http://dwight.natapp4.cc
  wechatOpenAuthorize: http://dwight.natapp4.cc
  sell: http://dwight.natapp4.cc


